### PR TITLE
iprange: Fixup test to work on go-tip

### PR DESCRIPTION
**Pull request by johnSchnake**
go-tip recently introduced a change that caused this test to break.
The error message returned now includes the correct function name
that was called rather than always ParseInt.
See: https://github.com/golang/go/commit/3a67d595f50ff7d589d4a097e162707342f1bbc4

@zquestz @wallyqs @shobhit85

### CODE REVIEW

**Comment by johnSchnake** [comment]
Confirmed this was just introduced 5 days ago; our latest build on master (from a merge 8 days ago) was green but when I just reran it, it was red against go: tip.

LGTY?

**Comment by wallyqs** [comment]
LGTM, though maybe we should add`allow_failures` for go tip? (and add 1.7.1 series too probably)

**Comment by johnSchnake** [comment]
Adding 1.7.x sounds good; though I like it failing for tip since it makes us fix these things sooner rather than later.

**Comment by johnSchnake** [comment]
Added 1.6.3 and 1.7.1; all green now. Merging.

**Comment by wallyqs** [comment]
allow failures still show failing builds though sgtm too

**Pull request merged**
