### PR TITLE
tarhelper: Add support for custom entry handlers on tar/untar

### PR DESCRIPTION
**Pull request by krobertson**
This adds support for a CustomHandler slice onto Tar and Untar. This
allows the caller to pass in function handlers that can be called to
customize the handling around specific entries.

Support to inject custom transformations is necessary to handle inline
conversion handlers for multiple union filesystems in the Continuum
codebase. We'll have this work by on the fly adapting to/from what we'll
officially utilize in the base packages to what the local host is
configured to use.

Change is part of #ENGT-9504.

review: @zquestz @jpoler 
cc: @earlruby

### CODE REVIEW

**Comment by zquestz** [comment]
LGTM

**Comment by jpoler** [comment]
LGTM, I like tests. Do we know specific use-cases for the custom handlers yet, or is this just a "We will probably encounter the need for this" kind of thing?

**Comment by krobertson** [comment]
The PR description has the use case. It is around aufs and overlay compatibility.

**Comment by jpoler** [comment]
Yeah, I was wondering what we would be changing specifically during the override, like changing particular header values, etc. The change looks good nonetheless.

**Comment by krobertson** [comment]
It is for whiteout files, which indicate things like files deleted in from a lower layer in a higher layer. The referenced ticket has the full details on it.

**Comment by krobertson** [comment]
Pausing the merged until the release is taken...

**Pull request merged**
