### PR TITLE
Switch from godep to gvt for wsconn

### PR DESCRIPTION
**Pull request by y0ssar1an**
Resubmit of #40, except it doesn't update gorilla/websocket this time.
Also adds `GO15VENDOREXPERIMENT=1` to `travis.yml` because that's a requirement for it to build on Go 1.5. It sets Travis to not run `go vet ./...`, etc. on vendored code.

Update: The version of gorilla/websocket currently vendored fails a `go vet` check, so we should update it after this PR is merged.

@krobertson @alextoombs @zquestz

### CODE REVIEW

**Comment by alextoombs** [comment]
I'd still break out the `travis.yml` change into a separate commit. Otherwise, LGTM if system tests on Continuum pass with this branch.

**Comment by y0ssar1an** [comment]
Ok. I broke it up into two commits 👍

**Comment by krobertson** [comment]
LGTM

**Comment by alextoombs** [comment]
LGTM

**Comment by alextoombs** [comment]
Do you have links for the system test runs, btw?

**Pull request merged**
