### PR TITLE
Add image history to served mock nats content

### PR DESCRIPTION
**Pull request by alextoombs**
In order to perform better tests of Docker image fetch functionality, we
need to make assertions about layers returned. Many image fetching
libraries, including docker2aci, require history to be returned, lest
they panic.

@tcahill @wallyqs @krobertson

### CODE REVIEW

**Comment by alextoombs** [comment]
[Continuum unit tests](http://tc.apcera.net/viewLog.html?buildId=253151); hope I didn't break any of my stupid assertions in the package manager's unit tests.

/cc @carlos-lopez-garces @shobhit85

**Comment by tcahill** [comment]
[LGTM](http://lgtm.in/i/g4wwc7aaq)

**Comment by krobertson** [comment]
LGTM... not sure what @tcahill is saying :P

**Comment by wallyqs** [comment]
LGTM

**Pull request merged**
