### PR TITLE
docker: store user info in *url.Userinfo instead of string 

### PR DESCRIPTION
**Pull request by johnSchnake**
The eventual use of the user info string is for placement into
basic auth headers which get base64 encoded and do not expect
to be percent encoded. As a result, auth will fail unless you
unescape this string later.

This change removes the need to unescape by setting the user info
with the raw username and password.

@alextoombs @wallyqs @shobhit85 
fyi @tedtong

### CODE REVIEW

**Comment by wallyqs** [comment]
... LGTM

**Comment by alextoombs** [comment]
How did this work in the Q1 release? (2.0.2) Did the Go stdlib change in its handling of usernames/passwords in URLs?

**Comment by johnSchnake** [comment]
@alextoombs Any check we did against a v2 registry would have fallen back to using v1 logic since when hitting the `/v2` endpoint it got a 404.  After go1.5.x you get the expected 401 which would have worked if you didn't have those special chars in your username/password.

**Comment by alextoombs** [comment]
Good call. LGTM

**Comment by wallyqs** [comment]
should we merge?

**Comment by johnSchnake** [comment]
@wallyqs No so this has changed a large degree since tests failed when I ran after getting LGTM.

The problem was that different places expected % encoded (putting it straight into a url type object) and others didnt (passing it into url.UserPassword).  Since it was a string it was hard to keep straight even if we just added comments.

I've changed it so that it serializes correctly even when using a real `url.Userinfo` object (normally wont serialize).  Just working out some kinks now.

**Comment by johnSchnake** [comment]
Will put up a PR to fix the separate (and nonrelated) unit test failures and rebase this branch. Just a problem with some test expectations but I'd like to separate that out into another PR.

**Comment by johnSchnake** [comment]
Just fixed the test problem with gotip; travis runs are green now. It was a change to just the test expectations not the package logic itself so it shouldn't invalidate any of the other testing results up to this point.

**Pull request merged**
