### PR TITLE
Add events client

### PR DESCRIPTION
**Pull request by alextoombs**
This adds a sample client for the events API using WAMP-over-websockets
from the `turnpike` library. It vendors that library along with the client,
and exposes a simple API for subscribing to events from FQNs.

It also includes the Event payload wrapper that we unmarshal events into.

Fixes #ENGT-7807

@shatrugna @shobhit85 @wallyqs 

cc @tstatler

I know this is hard to review; if you look at the first (unbuildable) commit, it includes just the functional change. The second commit is the vendoring.

I'd like to try to test this more thoroughly prior to merging.

### CODE REVIEW

**Comment by alextoombs** [comment]
I may try to refactor this to expose an interface satisfied by `turnpike.Client` to allow for easier testing; i.e, no websocket listener required.

**Comment by shatrugna** [comment]
As part of this, it probably won't be such a bad idea to use a forked
turnpike.v2 (under org Apcera). What do you think?

**Comment by alextoombs** [comment]
@shatrugna: probably not a bad idea, but then we'd have to vendor and track all of the dependencies as well. IMO, I'd just prefer to keep it like this for now.

**Comment by alextoombs** [comment]
I tested this independently from APC with a small Go program:

```
// Copyright 2016 Apcera Inc. All right reserved.

package main

import (
	"fmt"
	"os"
	"time"

	"github.com/apcera/util/events"
)

func main() {
	bearerToken := os.Getenv("CNTM_TOKEN")
	if bearerToken == "" {
		fmt.Fprintln(os.Stderr, "No bearer token provided via $CNTM_TOKEN")
		os.Exit(1)
	}

	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: `CNTM_TOKEN=\"Bearer ...\" events_main https://api.<cluster>/v1/wamp <job-fqn>")
		os.Exit(1)
	}

	wampServerURL := os.Args[1]
	streamFQN := os.Args[2]

	fmt.Printf("Creating WAMP client against %q with token %q...\n", wampServerURL, bearerToken)

	client, err := events.NewWAMPSessionClient(wampServerURL, bearerToken, "com.apcera.api.es")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create WAMP client: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("Done; streaming %q...\n\n", streamFQN)
	if err := client.StreamEvents(os.Stdout, streamFQN, time.Minute); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to stream %q: %s\n", streamFQN, err)
		os.Exit(1)
	}
}
```

[Persisted here](https://play.golang.org/p/DoJAbToXQJ) for good measure.

It works against a live cluster as well.

**Comment by shatrugna** [comment]
LGTM

**Pull request merged**
