### PR TITLE
Vendor gorilla/websocket in wsconn with gvt

### PR DESCRIPTION
**Pull request by y0ssar1an**
Move wsconn from `godep` to `gvt`.
Update websocket to v1.0.0.

@krobertson @alextoombs @zquestz

### CODE REVIEW

**Comment by alextoombs** [comment]
What's the impetus for this change?

cc @wallyqs @shobhit85 @shatrugna; may affect your lives.

**Comment by y0ssar1an** [comment]
I needed to vendor it in Kurma, and for whatever reason (probably something to do with import rewriting), Kurma's godep-vendored `wsconn` wouldn't build.

**Comment by krobertson** [comment]
It looks like the update broke one of the unit tests.

**Comment by krobertson** [comment]
+1 to Alex's comment, likely just do a test run of the core system tests. As long as those all pass, should be good.

**Comment by alextoombs** [comment]
We have active development of WAMP-over-websockets that's a priority for the June 3rd feature freeze. I'd like that team (cc'd above) to review this change to ensure it's not risky before we merge this.

Otherwise: can you break this change out into separate commits, please?

1. `godep` -> `gvt`

2. Update `wsconn`

3. Add env var to `.travis.yml` file

(possibly more)

**Comment by y0ssar1an** [comment]
I'll close this and resubmit a PR that doesn't update websocket.

**Pull request closed without merging**
