### PR TITLE
Write ping messages on a timer; instead of pong messages.

### PR DESCRIPTION
**Pull request by schancel**
@krobertson @wallyqs 

Should have noticed that this was OpPong when I updated this library awhile ago... Oops

### CODE REVIEW

**Comment by krobertson** [comment]
LGTM

**Comment by wallyqs** [comment]
LGTM thanks

**Comment by schancel** [comment]
@wallyqs There's some test failure.   Can you look at it?

**Comment by wallyqs** [comment]
Taking a look

**Comment by wallyqs** [comment]
Looks like it is due to a failure from the `s3util` package within the repo. I think can be fixed out of the scope of this PR.

**Pull request merged**
