### PR TITLE
Fix mode logic to preserve setuid bit

### PR DESCRIPTION
**Pull request by zquestz**
@krobertson @olegshaldybin @mbhinder

### CODE REVIEW

**Comment by krobertson** [comment]
NOTE: rebase off master to fix the tests... merged the PR Poler had to fix that. Didn't realize he never merged it.

**Comment by krobertson** [comment]
LGTM

**Comment by olegshaldybin** [comment]
Did anyone figure out why this fixes setuid handling? I am puzzled, the change looks good but I don't understand how this was preventing setuid from being carried over.

**Comment by krobertson** [comment]
Further up, tar.FileInfoHeader is used which has all the support for all special mode flags:https://golang.org/src/archive/tar/common.go?s=5701:5766#L194

However, the "mode" variable comes from FileInfo.Mode(), which I believe strips out some of the flags.

**Comment by olegshaldybin** [comment]
@krobertson: FileInfo.Mode() should respect all flags, it comes from os.Stat... weird that it doesn't pick it up.

**Comment by krobertson** [comment]
Ah, found more info. The value of the setuid bit in the tar spec is different than the filesystem. Tar package has a private constant for the setuid bit and others, and it doesn't match os.ModeSetuid.

**Comment by olegshaldybin** [comment]
Got it, makes sense: the assignment doesn't make sense, as the structure of tar header and os.FileMode doesn't match at all.

Change likely needs a test.

**Comment by olegshaldybin** [comment]
I pushed up a simple test. Change LGTM.

**Pull request merged**
