### PR TITLE
testtool: Use DeepEqual

### PR DESCRIPTION
**Pull request by johnSchnake**
Previously we were skipping over unexported fields silently which
gives misleading results in many situations (e.g. two different
byte buffers with different contents would pass TestEqual)

Also added one more helper (TestNotMatch).

@zquestz @y0ssar1an

Note: For the moment I left the unit tests, though they seem pointless to me now. Also, I did leave some of the special nil handling since I wasn't 100% sure right away if those were still helpful; I know there are some gotchas when it comes to DeepEquals and some nil-related cases.

### CODE REVIEW

**Comment by y0ssar1an** [comment]
Wouldn't this break lots of tests? We're suddenly comparing all the private struct members that weren't being compared before.

**Comment by johnSchnake** [comment]
Yup, so I'm simultaneously working on those. However, it is good and right that things break when you go from _not_ comparing them, to comparing them. This clearly produces bugs and should be fixed.

**Comment by johnSchnake** [comment]
It has been difficult to debug some tests due to the lack of feedback from DeepEqual. Should be able to read unexported data, just not write to it. Hoping there may be a way to adapt this. Many of the changes here still apply though (updating signatures, etc)

**Comment by johnSchnake** [comment]
Pretty sure that my alternate branch is superior to this; it is a little more forgiving than true DeepEquals but also maintains helpful output for testing.

**Pull request closed without merging**
